plants = [
    {"name": "Snake Plant", "humidity_range": (30, 50), "temp_range": (15, 28)},
    {"name": "Fiddle Leaf Fig", "humidity_range": (40, 60), "temp_range": (18, 24)},
    {"name": "Spider Plant", "humidity_range": (40, 80), "temp_range": (15, 30)},
    {"name": "Peace Lily", "humidity_range": (40, 70), "temp_range": (18, 28)},
    {"name": "Pothos", "humidity_range": (30, 60), "temp_range": (18, 30)},
    {"name": "Boston Fern", "humidity_range": (60, 90), "temp_range": (15, 25)},
    {"name": "Calathea", "humidity_range": (50, 80), "temp_range": (18, 26)},
    {"name": "Aloe Vera", "humidity_range": (40, 50), "temp_range": (13, 29)},
    {"name": "Golden Pothos", "humidity_range": (50, 70), "temp_range": (18, 24)},
    {"name": "Moth Orchid", "humidity_range": (40, 70), "temp_range": (15, 32)},
    {"name": "ZZ Plant", "humidity_range": (30, 50), "temp_range": (15, 27)},
    {"name": "Rubber Plant", "humidity_range": (40, 60), "temp_range": (15, 29)},
    {"name": "Monstera", "humidity_range": (60, 80), "temp_range": (18, 30)},
    {"name": "Philodendron", "humidity_range": (40, 60), "temp_range": (18, 26)},
    {"name": "Dumb Cane", "humidity_range": (50, 70), "temp_range": (15, 30)},
    {"name": "Bird’s Nest Fern", "humidity_range": (60, 80), "temp_range": (18, 24)},
    {"name": "Chinese Money Plant", "humidity_range": (40, 60), "temp_range": (15, 24)},
    {"name": "Jade Plant", "humidity_range": (30, 50), "temp_range": (10, 24)},
    {"name": "Parlor Palm", "humidity_range": (40, 60), "temp_range": (15, 26)},
    {"name": "Croton", "humidity_range": (40, 70), "temp_range": (18, 24)},
    {"name": "English Ivy", "humidity_range": (40, 60), "temp_range": (12, 22)},
    {"name": "Majesty Palm", "humidity_range": (50, 80), "temp_range": (15, 26)},
    {"name": "String of Pearls", "humidity_range": (30, 50), "temp_range": (18, 24)},
    {"name": "Anthurium", "humidity_range": (60, 80), "temp_range": (18, 24)},
    {"name": "Bird of Paradise", "humidity_range": (50, 70), "temp_range": (18, 30)},
    {"name": "Polka Dot Plant", "humidity_range": (50, 70), "temp_range": (15, 24)},
    {"name": "Aglaonema", "humidity_range": (40, 60), "temp_range": (18, 24)},
    {"name": "Hoya", "humidity_range": (40, 60), "temp_range": (15, 26)},
    {"name": "Dracaena", "humidity_range": (30, 60), "temp_range": (18, 27)},
    {"name": "Banana Plant", "humidity_range": (50, 80), "temp_range": (20, 30)},
    {"name": "Cast Iron Plant", "humidity_range": (30, 50), "temp_range": (10, 27)},
    {"name": "Alocasia", "humidity_range": (60, 80), "temp_range": (18, 26)},
    {"name": "Prayer Plant", "humidity_range": (50, 80), "temp_range": (18, 26)},
    {"name": "African Violet", "humidity_range": (40, 60), "temp_range": (18, 24)},
    {"name": "Spiderwort", "humidity_range": (40, 60), "temp_range": (15, 26)},
    {"name": "Areca Palm", "humidity_range": (50, 70), "temp_range": (18, 26)},
    {"name": "Bromeliad", "humidity_range": (60, 80), "temp_range": (15, 27)},
    {"name": "Umbrella Tree", "humidity_range": (50, 70), "temp_range": (18, 30)},
    {"name": "Silver Pothos", "humidity_range": (40, 60), "temp_range": (18, 27)},
    {"name": "Cactus", "humidity_range": (20, 40), "temp_range": (10, 30)}
]